### ISSUE TITLE
Move Tool

### ISSUE THREAD

**Issue by bpippin76** [juliandescottes/piskel#256]
I would love to be able to select multiple frames and get to move all of them simultaneously within the canvas.  Right now I'm only able to move one at a time, and I might not get them lined up correctly.  
Thanks again!!

**Comment by juliandescottes** [comment]
I could reuse the SHIFT / CTRL modifiers to target all frames/all layers/both, as we do in some other tools (Paint all, Rotate, Flip). SHIFT + Move already has a secret feature attached to it, but it can be remapped to ALT + Move.

**Comment by juliandescottes** [comment]
Will try to play with this before v0.5 :)

**Comment by juliandescottes** [comment]
Using shift now moves all frames from the current layer.
Using ctrl moves frames from all the layers at the current index.
Using ctrl+shift moves all frames in all layers.

**Comment by bpippin76** [comment]
That's great!  This will be an awesome addition.

**Comment by juliandescottes** [comment]
Released with v0.5.5.1

**Comment by bpippin76** [comment]
Hey Julian-
I hope all is well. I have a question, and I'm unable to find answers on
the web. I've saved a Piskel file on my PC, and now I'm trying to open it
on a Mac, with no luck. Is this not possible?
Thanks again for such great software!

Best regards -
Brian Pippin

**Comment by juliandescottes** [comment]
Hi, this should be possible but I'd need more details about what you are trying to achieve:
* are you using web or desktop versions on PC/Mac 
* if desktop version, which version on each
* how are you saving your piskel ? Piskel account gallery ? As a .piskel file? If it's as a file, please zip it and attach it here

In theory if you are still able to open your save on Windows, there's no reason it can't be opened on a Mac. 

That being said, can you please open a separate issue for this new question rather than commenting on this issue which is already closed :)
