### ISSUE TITLE
Feature: Copy from one piskel to another

### ISSUE THREAD

**Issue by dosjos** [juliandescottes/piskel#272]
Somethimes I create something in one piskel that I want to use in another piskel. To get the element over does seems impossible at the moment.

Idealy I would like to copy in one piskel and paste in another.

Possible workaround that don't work at the moment.
1. Create a piskel, draw something neat and save it.
2. Save it again under a different name
3. Edit the new save without destroying the first.

This would mean that when i rename a piskel, a new piskel is created, it is not actually renamed.

**Comment by juliandescottes** [comment]
I see at least two different use cases here : 
- copy/paste between two sprites (so just copying a portion of a frame)
- import a complete sprite into another one

You confirm you're talking about the first option here ?

I think we can fix this quite easily. We just need to share the copy/paste content via LocalStorage and that should do it.

**Comment by dosjos** [comment]
Yes, the first use case is what I have needed.
Although, someone might be happy for the second case as well

**Comment by austinblanchard** [comment]
The second case you mentioned ("import a complete sprite into another one") is exactly what I came on here to find. Any implementation for this yet? Thanks!

**Comment by juliandescottes** [comment]
@austinblanchard not yet, but thanks for the feedback. Helps to prioritize.

**Comment by deweytyl** [comment]
Also looking for number 2, but seems like number 1 would solve the same situation.

**Comment by lavadragon7i** [comment]
Is this thread still active? I kinda need #1

**Comment by cbear1** [comment]
dude no 2 would be really helpful

**Comment by juliandescottes** [comment]
> copy/paste between two sprites (so just copying a portion of a frame)

Was implemented by @PSeitz in #579 

> import a complete sprite into another one

Is being implemented in #285

**Comment by clebs** [comment]
Hello,
sorry to reopen this, but I am trying to copy a selection from one piskel to another in the browser and it does not seem to work...
Was this feature removed or is incompatible with the latest version of chrome?

**Comment by juliandescottes** [comment]
@clebs just tried on latest chrome on OSX and works for me.

My steps are:
- draw something in sprite 1
- select it
- copy (cmd/ctrl + C)
- switch to sprite 2
- paste (cmd/ctrl + V)

What are the exact steps you are doing?

**Comment by clebs** [comment]
Hi @juliandescottes!

I investigated further and found out what is happening. It seems the target piskel canvas needs to be equal or bigger in size than the source canvas.

So if I try to copy a small selection of a big image into a small image (where the selection would fit) it does not work.
Probably, the reason is that the pasting is done in absolute position, so I can't choose where to paste inside the target canvas, it has to be the same position as in the source canvas.

I am not sure if this is intended or indeed a bug.

Thanks for your quick response!

**Comment by Stabnormality** [comment]
@clebs 

While I doubt this issue still affects you, I found a fairly simple workaround and will share it for others who came here with the same problem.

To paste a selection from a large canvas to a small canvas, resize the small canvas to the same size as the large one. Make a new frame (or use the starting frame if you are working from the pasted selection). Now that the canvas is large, you can paste the image without issues. Next, move the pasted selection to the top left corner of the frame and reduce the canvas size back to the original, smaller version. I've tested this and it works. :)

**Comment by AxeLanderMoreira** [comment]
As of v0.14.0 Linux build, I can confirm this issue still happens. 

Since this is the latest official version for +4 years, I guess it is intended (or it won't likely be fixed anyway). 

Regardless, I found another workaround that is apparently more simple than the one shared by @Duoquadragesimal , so I will list the steps below:

To paste a selection from a large source canvas to a small destination canvas:

* No need to resize the destination canvas at all.
* On the source canvas, use the Move (M) tool to position the frame/portion you want to copy/paste to the top-left corner of the viewport.
* With the Rectangle Select (S) tool, mark the area that you want to be copied. Note: the bottom-right corner coordinates must be smaller than the destination canvas, otherwise it will be cropped upon pasting.
* Press Ctrl+C
* On the destination canvas, press Ctrl+V, and use Move (M) tool to adjust the position of the copied sprite.
* Back on the source canvas, press Ctrl+Z until it returns to normal, otherwise it will remain cropped. That way, you can keep repeating the above steps to copy other portions of the source canvas into new frames of the destination canvas.

Voilà. It should have worked. I am using this method to copy frames from a PNG spritesheet that is all out of aligment, into a more organized Piskel project.

Note: This works with two instances of the Piskel desktop client for Linux, but I suppose it works across all desktop and web clients.
