### ISSUE TITLE
Move & Selection tool

### ISSUE THREAD

**Issue by AlexHolly** [juliandescottes/piskel#290]
Is there a way to move a Selection without cut and paste it?
After a selection i can onlye move the selection box without the pixels inside.

When i switch to the selection tool i have sometimes to click once in the draw area to get the selection tool to work.Is it a bug?

**Comment by juliandescottes** [comment]
> Is there a way to move a Selection without cut and paste it?

That's the only way currently. There are other issues requesting move/selection improvements.

> When i switch to the selection tool i have sometimes to click once in the draw area to get the selection tool to work.Is it a bug?

That's a bug !

**Comment by TheThirdOne** [comment]
@juliandescottes, would you be open to a PR for changing the move tool so that when it is clicked on top of a selection it will only move the selection?

**Comment by juliandescottes** [comment]
@TheThirdOne sure ! Having the selection persistent between tools will be really cool. Could then use it for the paint bucket.

Right now we have one 'overlay' frame which we use to draw all the temporary pixels, before committing them to the real frame. Each tool is responsible for drawing the overlay frame. 

I think the easiest will be to stop using this overlay frame for the selection. We can either use a similar overlay frame, or even switch to a completely different display, using a DOM element here. Using another frame will probably be faster for a first version.

**Comment by TheThirdOne** [comment]
@juliandescottes, I got it working, but I have a few questions before I submit a PR.

1. Why does pskl.selection.BaseSelection exist when you could use pskl.tools.drawing.selection.BaseSelection? I had to move a function over from pskl.tools.drawing.selection.BaseSelection into pskl.selection.BaseSelection to make   it work.
2. What do you think about leaving the selection around the entire time? With your current code the selection is deleted immediately; I had to modify it to leave the selection in place. Should the selection stay visible? Should there be a way to delete it?
3. I'm not sure how ctrl-z works, but for some reason it works correctly which surprises me.

**Comment by juliandescottes** [comment]
> 1. Why does pskl.selection.BaseSelection exist

pskl.tools.drawing.selection.BaseSelect is the tool : what should be done when user moves the tool, clicks, starts dragging etc ...
pskl.selection.BaseSelection is the object that represents selected pixels and has some utility functions associated to it. The bare minimum is that the selection should hold the selected pixels. Utility functions can be reviewed one by one, no worries.

Before moving a method out of the Selection class, the only question to ask is probably whether this could be called from the selectionManager.

(That being said you should also be able to call selectionTool.selection.yourMethod() ?)

> 2. What do you think about leaving the selection around the entire time

Makes sense. Dismiss it when the user presses ESC (the key is already used to close dialogs, so we will need to modify ShortcutService in order to accept shortcuts to be stacked for the same key).

> 3. I'm not sure how ctrl-z works, but for some reason it works correctly which surprises me

The HistoryService is handling the undo/redo. PISKEL_SAVE_STATE events are raised by the tools (and some other classes, such as the SelectionManager). The event contains all the information necessary to replay the action (most of the time it's a callback to the tool with some arguments). Periodically, we store a SNAPSHOT of the whole sprite instead of a simple save state.

So what happens when you CTRL+Z is that you actually go back a few states, to the latest SNAPSHOT, and then we replay everything until state N-1.

I don't really know what / how you implemented your change, but since the 'selection' information is not persisted in the save states, I think we should have some problems here. Typically I'm thinking about the following : 
- paint all pixels black
- select an area in the center
- switch to move tool
- move the selection once
- move the selection twice
- unselect 

When replaying the first 'move' it should move the whole frame as the selection information will be lost.

Again, would need to see what you did :) Don't hesitate to submit a PR, will be easier to discuss maybe ?

**Comment by juliandescottes** [comment]
@TheThirdOne  And by the way thanks a lot for having a look, that's awesome :)

**Comment by Wakintosh** [comment]
When would you think that the movement feature will be implemented?

**Comment by TheThirdOne** [comment]
I started working on other projects and forgot I was working on this. I might be able to  complete it by thanksgiving break. Otherwise I can have it done in 2 weeks.

**Comment by juliandescottes** [comment]
Having a stab at this at the moment. 

Will implement a new modifier for the selection tools: when holding shift while dragging the selection, the content will move as with the selection.

**Comment by juliandescottes** [comment]
This has been implemented and released.

You can move the current selection by holding shift and dragging the selection. Closing.
