### ISSUE TITLE
Save shortcut

### ISSUE THREAD

**Issue by applesarefum** [juliandescottes/piskel#313]
Not sure if this has already been submitted. Adding a CTRL+S (CMD+S for Mac) shortcut to save would be a good idea, I'm not sure if this already exists in the desktop version, but it doesn't in the browser version.

**Comment by juliandescottes** [comment]
Hi ! 

Issue already exists and is almost implemented : #277 :)

I would be interested to know if you are usually saving to a piskelapp account or to a different target.
My current implementation automatically saves to the gallery if possible.
Otherwise it falls back to a local browser save. I'm not sure if users would prefer local browser save vs file (.piskel) download.

Any input ?

**Comment by applesarefum** [comment]
I usually save to the gallery through the side menu. CTRL+S opens the save dialogue and tries to save the page as an MHTML file, and CTRL+SHIFT+S does nothing as far as I'm aware

**Comment by juliandescottes** [comment]
It is "almost" implemented, and not released yet. 

For CTRL SHIFT S it would be cool if it could save as a New Piskel directly but that will be more complex.

Thanks for the info, I will close this issue now. You can comment on #277 if needed !
