### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by staab** [juliandescottes/piskel#374]
A memory leak occurs with higher resolution piskels. I have a 300x300 canvas with three layers and 42 frames. I'm probably misusing Piskel a bit by doing a sketchy rendering first (lots of small, short lines like I would on paper). At any rate, piskel would max out at 1.6GB of RAM then start crashing tabs. I really enjoy piskel, but this makes it very limiting.

**Comment by juliandescottes** [comment]
As you guessed Piskel was not really designed for high resolution sprites :/

The performance is not good and the memory usage is not good either. One of the things that drain a lot of memory is to maintain the sprite history to allow undo/redo. Every 50 user action, a backup of the sprite is stored in memory, as a checkpoint from where I can replay the actions.

I guess we could store only one backup, and write the others to indexeddb.

**Comment by staab** [comment]
That sounds about right. I was also looking around in the data stored in memory, and it looks like you store pixels as an array of rgba strings? You could store them much more compactly using typed arrays  or whatnot. I noticed you use tinycolor. It looks like a really nice library, but if you're using a separate instance for each pixel, I could see it getting heavy fast. You could also use some sort of immutable/persistent data structure for representing pixels so you'd only have to store an instance of each.

Anyway, just my two cents. From my brief perusal of your code, it looks like you know what you're doing better than I.

**Comment by juliandescottes** [comment]
> looks like you store pixels as an array of rgba strings? 

Ahah yes, not proud of this! Need to take some time to experiment with alternative models. The color palette is normally pretty small for pixel art, I thought about using a palette map + array of palette index. The first thing to do would be to assess the size difference with the existing model.

> tinycolor

To be reviewed, but it's normally used only to translate values from hex to rgb etc... I could be wrong, though. 

> You could also use some sort of immutable/persistent data structure for representing pixels

Can you elaborate a bit? Sounds interesting!

> it looks like you know what you're doing better than I.

Don't be so sure  :) Thanks for all the suggestions.

**Comment by staab** [comment]
Sure thing! Nice to see my casual suggestions so well received. 

As far as immutable/persistent data structures, [here's a link](https://en.wikipedia.org/wiki/Persistent_data_structure) in case you're not familiar with the general concept. [Immutablejs](https://facebook.github.io/immutable-js/) uses them to enable pass-by-value-ish semantics where desired without losing performance. And in many cases, you can gain performance as well by using less memory. I was thinking something along the lines of making a Layer an Immutablejs array of pixels. That way, if two layer had only a few different pixels, they could share references to the pixels they have in common, while using memory only for the differences. 

I'm not sure this would be right for you, given that you store each action in history - I'd think that they would have a lot less overlap.

**Comment by juliandescottes** [comment]
Finally starting to work on this.

First of all, I attach below a script here that can be used to stress the application.
Using it I identified three hotspots for memory consumption:
- src/js/service/HistoryService.js
- src/js/service/CurrentColorsService.js
- src/js/model/frame/CachedFrameProcessor.js

HistoryService should be modified in order to have a maximum number of recorded states (~500 to begin with? we could also make this limit depend on the complexity of the sprite).

CachedFrameProcessor is currently caching all frames displayed and clears its cache every 10 minutes. We should change the caching strategy to have a maximum amount of cached frames and start clearing up the least used entries (no need to do something too complicated in the beginning though).

CurrentColorsService needs more investigation. I remember I spawn a LOT of workers in order to compute the current colors. 

With temporary fixes for HistoryService & CachedFrameProcessor + disabling the CurrentColorService, I've been able to let the script run until 200 000 events have been replayed (I stopped it manually, but the memory consumption seemed pretty stable).  Without it, it usually fails for me between 10 000 and 20 000 events, after reaching 2+GB of memory used.

``` javascript
pskl.app.penSizeService.setPenSize(4);

var paint = function () {
    var color = {
        r: Math.floor(Math.random() * 256),
        g: Math.floor(Math.random() * 256),
        b: Math.floor(Math.random() * 256)
    };
    var hex = window.tinycolor(color).toHexString().toUpperCase();
    $.publish(Events.PRIMARY_COLOR_SELECTED, [hex]);
    var x = Math.floor(Math.random() * pskl.app.piskelController.getWidth());
    var y = Math.floor(Math.random() * pskl.app.piskelController.getHeight());
    var screenCoordinates = pskl.app.drawingController.getScreenCoordinates(x, y);
    var event = {
        "button": 0,
        "shiftKey": false,
        "altKey": false,
        "ctrlKey": false,
        "clientX": screenCoordinates.x,
        "clientY": screenCoordinates.y
    };
    pskl.app.drawingController.onMousedown_(event);
    pskl.app.drawingController.onMouseup_(event);
};

var events = 0;
window.setInterval(function () {
    for (var i = 0 ; i < 5 ; i++) {
        paint();
        events++;
        if (events/1000 === Math.round(events/1000)) {
            pskl.app.piskelController.createLayer();
        }
    }
}, 5);
```
