### ISSUE TITLE
Adjustable Scale for ZIP and GIF files

### ISSUE THREAD

**Issue by CDBiddulph** [juliandescottes/piskel#381]
When exporting a multi-frame piskel, there is an option to increase the scale of the image when you export it as a PNG spritesheet, but not for a ZIP or GIF file. You can get around it by resizing the piskel and checking "resize canvas content," but that takes unnecessary time and you have to scale it back if you want to change it later. It would be nice to be able to easily export it as a ZIP or GIF without it looking tiny.

**Comment by juliandescottes** [comment]
For the GIF export you can actually specify the export resolution. 

I think for GIF export it's nice to keep the flexibility of specifying the size down to the pixel, rather than use an integer scaling factor. 
If you upload to a platform which displays images at 300px width, you can set 300px as export width regardless of the original dimensions of the sprite.

One thing we could do is make the slider apply to all the export options. It would also update the width & height inputs of the GIF section live.

**Comment by juliandescottes** [comment]
> One thing we could do is make the slider apply to all the export options. It would also update the width & height inputs of the GIF section live.

Done, fixed with #472
