### ISSUE TITLE
Feature Request for Tiling

### ISSUE THREAD

**Issue by cra0zy** [juliandescottes/piskel#402]
It would be nice if there was a transform button that would take an image from:
12
34
and arrange it:
43
21

Something like if you would offset an image by half and wrapped it around in Gimp: https://youtu.be/yR5Sv20eluU?t=2m10s

**Comment by juliandescottes** [comment]
Sorry for not replying earlier! 

That sounds like a pretty advanced feature, but that should be easy to implement, and we do have an empty slot in the "transform" box :)

**Comment by cra0zy** [comment]
> That sounds like a pretty advanced feature, but that should be easy to implement, and we do have an empty slot in the "transform" box :)

Yey :D

**Comment by juliandescottes** [comment]
With the introduction of the seamless drawing mode + using the existing Move[1] functionality, I think you can achieve the same result quite easily (and feels more flexible):
 
![piskel-seamless-drawing](https://cloud.githubusercontent.com/assets/1141550/17138975/e14dc858-5342-11e6-8364-7412134c9dc2.gif)

[1] When using Move, hold ALT (OPTION on OSX) in order to achieve the same result as on the GIF above.

Closing for now, but feel free to reopen if what I presented above is not enough (however we no longer have an empty spot in the transform box, so this will have to come with design changes)

**Comment by cra0zy** [comment]
That looks awesome, Thank you!!
