### ISSUE TITLE
Feature request: Align to Center

### ISSUE THREAD

**Issue by fernandodiacenco** [juliandescottes/piskel#403]
Hi,

I would like to suggest the possibility of aligning the object on the center of the screen

Currently I have to export my files as png, open up on gimp and do some witchcraft to align to center, and for some reason that leaves the files slightly larger than the original Piskel ones

Thanks for the hard work!

**Comment by juliandescottes** [comment]
Thanks for opening this!

Some questions : 
- What do you mean by "object"? 
- Can you post some screenshots of a before/after to help me understand what we are after here ? 

Thanks!

**Comment by fernandodiacenco** [comment]
Oh thanks for answering!

I imagined something like this:

I make little thing

![01](https://cloud.githubusercontent.com/assets/2643364/13196892/cfa2b03c-d7c3-11e5-9e29-1cc0b10d0690.png)

I select it with rectangle selection or something

![02](https://cloud.githubusercontent.com/assets/2643364/13196899/fed44ff0-d7c3-11e5-910f-37497b64b35d.png)

I press Piskel _Super Magic Button™_ to align the selected "object" to the center of the.. canvas or whatever its called

![03](https://cloud.githubusercontent.com/assets/2643364/13196903/40da65ce-d7c4-11e5-85cd-819a12ecbdbf.png)
 
Ta da!

**Comment by juliandescottes** [comment]
Thanks for detailed info, definitely helps.

So that could be : 
- if the user has a selection, move the selection to the center of the canvas
- if there is no selection, we could still detect the smaller non-transparent rectangle (ie. what you selected in your screenshot) and move that

I think that fits with the other "transform" tools on the right side. But that's a bit more advanced/edge-case than the current ones (rotate, flip and clone). Maybe we should introduce a kind of menu or configuration in order to access this kind of more advanced features.

**Comment by juliandescottes** [comment]
If anyone wants to pick this up, feel free to add it to the "transform" tools box.
Additional requirement on top of my previous comment:
- it should support CTRL/SHIFT to apply to all layers/frames, same as the Rotate and Mirror tool
- it should support undo/redo (ie send SAVE_STATE event, and provide a replay function)
- it should have an icon

The code for the transform tools is in src/js/tools/transform.
Look at the pskl.tools.ToolsHelper.getTargetFrames to implement the CTRL/SHIFT modifiers. 
Here I would advise not to reuse the AbstractTransformTool, which I will probably remove soon. But you can have a look at the implementation to see how state save&replay is handled.

**Comment by juliandescottes** [comment]
Feature added by @mattdinthehouse 
Closing the issue. Will be released in v0.8.0
