### ISSUE TITLE
Progress on third Milestone 

### ISSUE THREAD

**Issue by Tajnymag** [juliandescottes/piskel#416]
Hello, some time ago you announced that you are working on a new stable stable build. How is it going so far? Any new features coming? :-)

**Comment by juliandescottes** [comment]
Hi thanks for asking :) Last release was 0.6.0, end of December, in case you missed it.

Not sure which milestone/feature you are referring to. According to your past comments in this repository I'm going to assume you are after https://github.com/juliandescottes/piskel/issues/293 .
It is currently worked on by @GMartigny in https://github.com/juliandescottes/piskel/pull/401 . Feel free to comment in the issue or in the PR if you want.

Regarding the overall milestones/roadmaps:
I gave up on roadmaps and planning for Piskel, because I can never plan how much time I will have to work on it. I just do a release as soon as enough features have piled up !

Next release will be 0.7.0. For now there is not enough material to do one. I want to do it as soon as https://github.com/juliandescottes/piskel/issues/293 and https://github.com/juliandescottes/piskel/issues/414 are implemented.

I am closing this as this is not an "issue" per se. Feel free to reach out by email or twitter if you want/need some information.

**Comment by Tajnymag** [comment]
Oh, sorry for the confusion. I actually wrote that blindly while on being on a slow connection. Thanks for the answer. I won't annoy anymore :)

**Comment by juliandescottes** [comment]
Don't worry, no harm done :) Github is missing some kind of integrated forum I guess.

We could use the Gitter chat available at https://gitter.im/juliandescottes/piskel for this kind of discussions. Not sure if I can get email notifications from this tool.
