### ISSUE TITLE
Help with animation

### ISSUE THREAD

**Issue by matter123456** [juliandescottes/piskel#590]
I need help I'm not that good at animating so can someone give this guy a walking/running animation?
![characte](https://cloud.githubusercontent.com/assets/24624363/21288208/a5f5703e-c44a-11e6-8aa9-c5137c1589fa.gif)

**Comment by juliandescottes** [comment]
Hi @matter123456 

This issue tracker is used to report problems with the Piskel website/application, propose improvements and contribute code. The audience is more likely to be made of developers rather than artists/animators.

You should try to find dedicated forums on pixelart animation. Maybe http://pixeljoint.com/ ? 

I will leave your issue open for a few days in case someone can provide help or resources.
