### ISSUE TITLE
Pressing "d" for default colors doesn't fully work.

### ISSUE THREAD

**Issue by TALANTO** [juliandescottes/piskel#601]
Hello I want to thank you for the great app and share few bugs I've found to make it even better!

When I change the left and right mouse button colors and I press "d" for the default colors they are actually changed but it's not shown in the bottom left corner:

![screenshot from 2016-12-29 13-20-40](https://cloud.githubusercontent.com/assets/16134110/21544825/69526130-cdca-11e6-9df0-251951d40bff.png)

**Comment by juliandescottes** [comment]
Thanks for the bug report! 

The issue comes from PaletteController.js and the resetColors method. An option is to remove the reset method from the SelectedColorsService (since it doesn't fire the expected events anyway) and implement PaletteController::resetColors in the same way as PaletteController::swapColors

**Comment by juliandescottes** [comment]
Fixed by #605 , thanks to @Sal0hcine
