### ISSUE TITLE
Problem with saving as a .Piskel

### ISSUE THREAD

**Issue by CommanderLouiz** [juliandescottes/piskel#608]
I've got a large (400 frame) piskel I'm trying to "Save as" to my computer, but no matter what I name it, or where I save it, it saves it as a .Piskel that when attempting to open through the app, opens nothing. When I right-click on the file, and check its properties, it has a file size of 4KB! Meanwhile I have another .Piskel with a size of 32KB. Is there a max size for piskel files?

### Steps to reproduce the bug
1. Download attached .Gif (372KB)
2. Import it
3. Save as
4. Rage when you try and open it.
![dual_space_v2](https://cloud.githubusercontent.com/assets/24998644/21756810/ad6270ee-d5eb-11e6-8ef9-abe4771cf90c.gif)

### Environment details
* operating system: Windows 10
* Offline application, Version 0.6.0, realized it was outdated, updated to 0.8.0, same problem.

### Sprite details
* number of frames: 400
* sprite resolution: 100x60
* session duration: 12:00-3:30PM, exported as .gif halfway through. Resumed 8:00PM-9:20PM from .gif

Note: I can still export it as a .gif, and re-import it, and it works fine. It just takes longer to save it as a gif.

**Comment by juliandescottes** [comment]
Thanks for the detailed report! 

With 400 frames, the image I generate to store your sprite is too big and results in an empty image.

This issue is fixed in 0.10.0 which should be released later this week:
* you will get a warning when your sprite starts exceeding the capabilities of Piskel (#555)
* saving as .piskel will work for bigger sprites (#591)

> When I right-click on the file, and check its properties, it has a file size of 4KB! 
> Meanwhile I have another .Piskel with a size of 32KB. Is there a max size for piskel files?

The 4KB file size is because the generated image was empty. Even with the limitations of the current implementation we can easily have > 1MB .piskel files generated.

**Comment by juliandescottes** [comment]
@CommanderLouiz you can try a test version of the new release for windows at https://drive.google.com/uc?export=download&id=0BwPjxqZA0YlRN3k1aElKV2hNbjQ

**Comment by CommanderLouiz** [comment]
I have downloaded that beta, and successfully saved the file as a .Piskel. It has a size of 77KB.

I did get the performance warning in the bottom right.

Thank you for fixing this!

**Comment by CommanderLouiz** [comment]
Ok, I'm home now, (I downloaded that beta on a different computer), and when I try to run Piskel, Norton is claiming ffmpeg.dll is a medium level risk under the category of Insight Network Threat? It removed it from my computer. I restored it, but I'm wondering why it was removed to begin with.

**Comment by juliandescottes** [comment]
Thanks for the info. Honestly I have very little control over the build process for the desktop versions of Piskel. I'll do a scan on my computer in case something got infected.

If you want to build for windows by yourself, the instructions are at https://github.com/juliandescottes/piskel/wiki/Building-desktop-applications . You might need to follow https://github.com/juliandescottes/piskel/wiki/Development-Environment first.

**Comment by juliandescottes** [comment]
Local scan is clean on my computer... I don't know why Norton is getting triggered in your case.

**Comment by juliandescottes** [comment]
I can see references to Norton triggering false positives on those dlls (eg https://forum.smithmicro.com/topic/296/norton-security-false-positives-p11-sr4-11-0-4-32600/3)

Which version of Norton are you using?

**Comment by juliandescottes** [comment]
And from what I can read, "Insight Network Threat" means Norton hasn't really seen the file enough to trust it, not that it contains a virus. 

I don't know if it matches those dlls with other similar dlls or not. But since I just released this beta version of Piskel, I guess we can't expect Norton to find it installed on many other machines. 

Anyway, not much I can do here :(

**Comment by CommanderLouiz** [comment]
It did say the file was newly released, which I figured made sense. Didn't know that's what insight network threat meant. It's whatever the latest version is. Just updated it recently.
