### ISSUE TITLE
It won't let me edit my sprite

### ISSUE THREAD

**Issue by Apersononline** [juliandescottes/piskel#666]
Bug description

When I go to my gallery to edit a sprite/animation I called COLORBARS, I click to edit it and there's nothing there! I had this happen to me before and I ended up almost restarting the whole thing (I recovered about 5 slides out of 20). Please tell me if there is any way to fix it!

* operating system:
* browser

* stuck at 87 frames
* sprite resolution: 200x200
* session duration:12fps
![image](https://cloud.githubusercontent.com/assets/28007472/25387294/37309a44-297f-11e7-8325-f2729654138e.png)

**Comment by juliandescottes** [comment]
Hi,

I can see a 72 frames long animation set as the latest saved version for this sprite.
The content seems valid so I think it should load correctly when you try to edit your sprite.

I can't test it directly since this is a private sprite but you should be able to load http://www.piskelapp.com/p/agxzfnBpc2tlbC1hcHByEwsSBlBpc2tlbBiAgICv4JSgCgw/edit ?
If it doesn't load for you, can I flip the sprite to a public one so that I can check it on my side?

I can't find any error on the server matching your sprite id so I assume you had a browser crash while working on the version that had 87 frames? Sadly, if there was indeed a browser crash there's not much we can do to recover it now :( 

When this happens your best bet is to reload the editor and open the import panel to try to restore your last session

**Comment by juliandescottes** [comment]
No feedback from @Apersononline , there is no actionable item for this issue. Closing.
